# Generated by Django 3.2.13 on 2022-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transactions',
            field=models.IntegerField(default=0),
        ),
    ]
