# Generated by Django 3.2.13 on 2022-05-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_user_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='klad_type',
            field=models.CharField(choices=[('SNOW', 'Снежный прикоп'), ('MAGNET', 'Магнит'), ('HIDE', 'Тайник'), ('GROUND', 'Прикоп'), ('OTHER', 'Другой')], default='GROUND', max_length=6, verbose_name='Тип клада'),
        ),
        migrations.AddField(
            model_name='zakladka',
            name='klad_type',
            field=models.CharField(choices=[('SNOW', 'Снежный прикоп'), ('MAGNET', 'Магнит'), ('HIDE', 'Тайник'), ('GROUND', 'Прикоп'), ('OTHER', 'Другой')], default='GROUND', max_length=6, verbose_name='Тип клада'),
        ),
    ]
