# Generated by Django 3.2.13 on 2022-05-21 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courier',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='courier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
