# Generated by Django 3.2.13 on 2022-05-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_auto_20220521_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tgbot.city', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
